### ISSUE TITLE
Migrate to Netlify

### ISSUE THREAD

**Issue by Jamesking56** [Jamesking56/WhichLaravel.me#27]
Migrate the site to Netlify. Migrating offers these benefits:

1. Netlify supports automatic deployment from Git and PR deploy previews.
2. We can instantly test any Dependabot updates as a PR deploy preview will be generated by Netlify
3. We can store Netlify config as code.

## Todo

- [x] Create Netlify Site and link to this repo.
- [x] Add Netlify config to this repo.
- [x] Setup Google Tag Manager and add to Cloudflare
- [x] Add custom domain `whichlaravel.me` to Netlify
- [x] Update DNS for `whichlaravel.me`
- [x] Disable GitHub Pages
